steps:
- name: 'gcr.io/cloud-builders/docker'
  script: |
    docker build -t ${LOCATION}-docker.pkg.dev/$PROJECT_ID/${REPO_FULL_NAME}:$COMMIT_SHA
  automapSubstitutions: true
images:
- '${LOCATION}-docker.pkg.dev/$PROJECT_ID/${REPO_FULL_NAME}:$COMMIT_SHA'