steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    script: |
      docker build -t ${LOCATION}-docker.pkg.dev/$PROJECT_ID/globe-and-citizen-docker-repo/${REPO_FULL_NAME}:$COMMIT_SHA .
    automapSubstitutions: true
    id: 'Build The Image'

  # Push the image to Google Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'push', '${LOCATION}-docker.pkg.dev/$PROJECT_ID/globe-and-citizen-docker-repo/${REPO_FULL_NAME}:$COMMIT_SHA' ]
    id: 'Push The Image'
    waitFor:
      - 'Build The Image'

      # Run the container in Cloud run
  - name: 'gcr.io/cloud-builders/gcloud'
    args: [ 'run', 'deploy', '--image', '${LOCATION}-docker.pkg.dev/$PROJECT_ID/globe-and-citizen-docker-repo/${REPO_FULL_NAME}:$COMMIT_SHA', '--region', '${LOCATION}', '--platform', 'managed', '--allow-unauthenticated' ]
    id: 'Deploy to Cloud Run'
    waitFor: [ '-' ]
    # Push the image to Google Container Registry
images:
  - '${LOCATION}-docker.pkg.dev/$PROJECT_ID/globe-and-citizen-docker-repo/${REPO_FULL_NAME}:$COMMIT_SHA'