steps:
- name: 'gcr.io/cloud-builders/docker'
  script: |
    docker build -t ${LOCATION}-docker.pkg.dev/$PROJECT_ID/${REPOSITORY}/${IMAGE}:$COMMIT_SHA
images:
- '${LOCATION}-docker.pkg.dev/$PROJECT_ID/${REPOSITORY}/${IMAGE}:$COMMIT_SHA'