version: '3.1'

services:

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5173:5173" # Map container port to the PORT environment variable
    volumes:
      - ./src:/app/src