version: '3.4'

services:

  app:
    build:
      context: .
      target: production
    ports:
      - "5173:80" # Map container port to the PORT environment variable
    volumes:
      - ./src:/app/src